data "aws_partition" "current" {}

locals {
  common_tags = merge(var.tags, { Name = var.identifier })
}

resource "aws_db_subnet_group" "this" {
  name        = var.identifier
  description = "Subnets for ${var.identifier}"
  subnet_ids  = var.subnet_ids

  tags = local.common_tags
}

resource "aws_db_parameter_group" "this" {
  name        = var.identifier
  family      = var.parameter_group_family
  description = "Parameters for ${var.identifier}"

  # rds.force_ssl is set unconditionally rather than exposed as a variable. A PostgreSQL
  # server that accepts plaintext connections has no defensible configuration inside a VPC,
  # and the parameter is static, so discovering it later costs a reboot.
  parameter {
    name         = "rds.force_ssl"
    value        = "1"
    apply_method = "pending-reboot"
  }

  dynamic "parameter" {
    for_each = var.parameters

    content {
      name         = parameter.key
      value        = parameter.value.value
      apply_method = parameter.value.apply_method
    }
  }

  # The name is part of the identity of the group, and RDS cannot rename one in place.
  # Creating the replacement first keeps the instance attached to a valid group throughout.
  lifecycle {
    create_before_destroy = true
  }

  tags = local.common_tags
}

resource "aws_security_group" "this" {
  name        = "${var.identifier}-rds"
  description = "Ingress to ${var.identifier} on port ${var.port}"
  vpc_id      = var.vpc_id

  tags = local.common_tags
}

resource "aws_vpc_security_group_ingress_rule" "from_security_group" {
  for_each = toset(var.allowed_security_group_ids)

  security_group_id            = aws_security_group.this.id
  referenced_security_group_id = each.value
  ip_protocol                  = "tcp"
  from_port                    = var.port
  to_port                      = var.port
  description                  = "PostgreSQL from ${each.value}"
}

resource "aws_vpc_security_group_ingress_rule" "from_cidr" {
  for_each = toset(var.allowed_cidr_blocks)

  security_group_id = aws_security_group.this.id
  cidr_ipv4         = each.value
  ip_protocol       = "tcp"
  from_port         = var.port
  to_port           = var.port
  description       = "PostgreSQL from ${each.value}"
}

# No egress rules at all. An RDS instance is a server: it answers connections and never
# opens one. An empty egress set is the correct configuration, not an oversight.

data "aws_iam_policy_document" "monitoring_assume" {
  count = var.monitoring_interval > 0 ? 1 : 0

  statement {
    effect  = "Allow"
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["monitoring.rds.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "monitoring" {
  count = var.monitoring_interval > 0 ? 1 : 0

  name               = "${var.identifier}-rds-monitoring"
  assume_role_policy = data.aws_iam_policy_document.monitoring_assume[0].json

  tags = local.common_tags
}

resource "aws_iam_role_policy_attachment" "monitoring" {
  count = var.monitoring_interval > 0 ? 1 : 0

  role       = aws_iam_role.monitoring[0].name
  policy_arn = "arn:${data.aws_partition.current.partition}:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole"
}

resource "aws_db_instance" "this" {
  identifier = var.identifier

  engine         = "postgres"
  engine_version = var.engine_version
  instance_class = var.instance_class
  port           = var.port

  allocated_storage     = var.allocated_storage
  max_allocated_storage = var.max_allocated_storage
  storage_type          = var.storage_type
  storage_encrypted     = true
  kms_key_id            = var.storage_kms_key_id

  db_name  = var.database_name
  username = var.master_username

  # The password is generated by RDS, written straight into Secrets Manager and rotated
  # there. It is never a Terraform variable, never in a tfvars file and never in state -
  # the only thing state holds is the ARN of the secret.
  manage_master_user_password   = true
  master_user_secret_kms_key_id = var.master_user_secret_kms_key_id

  db_subnet_group_name   = aws_db_subnet_group.this.name
  parameter_group_name   = aws_db_parameter_group.this.name
  vpc_security_group_ids = [aws_security_group.this.id]
  publicly_accessible    = false
  multi_az               = var.multi_az

  backup_retention_period  = var.backup_retention_period
  backup_window            = var.backup_window
  maintenance_window       = var.maintenance_window
  copy_tags_to_snapshot    = true
  delete_automated_backups = false

  deletion_protection       = var.deletion_protection
  skip_final_snapshot       = var.skip_final_snapshot
  final_snapshot_identifier = var.skip_final_snapshot ? null : coalesce(var.final_snapshot_identifier, "${var.identifier}-final")

  performance_insights_enabled          = var.performance_insights_enabled
  performance_insights_retention_period = var.performance_insights_enabled ? var.performance_insights_retention_period : null
  performance_insights_kms_key_id       = var.performance_insights_enabled ? var.storage_kms_key_id : null

  monitoring_interval = var.monitoring_interval
  monitoring_role_arn = var.monitoring_interval > 0 ? aws_iam_role.monitoring[0].arn : null

  enabled_cloudwatch_logs_exports = var.enabled_cloudwatch_logs_exports
  auto_minor_version_upgrade      = var.auto_minor_version_upgrade
  apply_immediately               = var.apply_immediately

  # IAM authentication is on unconditionally: it costs nothing, and it is what lets an
  # operator connect with a 15-minute token instead of the master password.
  iam_database_authentication_enabled = true

  tags = local.common_tags
}
