variable "identifier" {
  description = "DB instance identifier. Also the prefix of the subnet group, parameter group and security group."
  type        = string

  validation {
    condition     = can(regex("^[a-z][a-z0-9-]{0,61}[a-z0-9]$", var.identifier))
    error_message = "identifier must be 2-63 chars, lowercase letters, digits and hyphens, starting with a letter and not ending in a hyphen."
  }
}

variable "vpc_id" {
  description = "VPC the security group is created in."
  type        = string
}

variable "subnet_ids" {
  description = "Subnets of the DB subnet group. Use the intra subnets: an RDS instance has no reason to reach the internet."
  type        = list(string)

  validation {
    condition     = length(var.subnet_ids) >= 2
    error_message = "RDS requires a subnet group covering at least two availability zones, even for a single-AZ instance."
  }
}

variable "engine_version" {
  description = "PostgreSQL version. A major-only value such as \"16\" tracks the latest minor and lets AWS upgrade it inside the maintenance window."
  type        = string

  validation {
    condition     = can(regex("^[0-9]+(\\.[0-9]+)?$", var.engine_version))
    error_message = "engine_version must look like 16 or 16.4."
  }
}

variable "parameter_group_family" {
  description = "Parameter group family, for example postgres16. Must match the major version of engine_version."
  type        = string

  validation {
    condition     = can(regex("^postgres[0-9]+$", var.parameter_group_family))
    error_message = "parameter_group_family must look like postgres16."
  }

  validation {
    condition     = endswith(var.parameter_group_family, split(".", var.engine_version)[0])
    error_message = "parameter_group_family must end with the major version from engine_version (postgres16 for engine_version 16 or 16.4)."
  }
}

variable "instance_class" {
  description = "RDS instance class, for example db.t4g.medium or db.m7g.large."
  type        = string

  validation {
    condition     = can(regex("^db\\.[a-z0-9]+\\.[a-z0-9]+$", var.instance_class))
    error_message = "instance_class must look like db.<family>.<size>, for example db.m7g.large."
  }
}

variable "allocated_storage" {
  description = "Initial storage in GiB."
  type        = number
  default     = 50

  validation {
    condition     = var.allocated_storage >= 20 && var.allocated_storage <= 65536
    error_message = "allocated_storage must be between 20 and 65536 GiB."
  }
}

variable "max_allocated_storage" {
  description = <<-EOT
    Ceiling for storage autoscaling in GiB. Null disables autoscaling, which means the
    instance stops accepting writes the moment the volume fills.
  EOT
  type        = number
  default     = 200

  validation {
    # A plain `var.max_allocated_storage == null || var.max_allocated_storage > ...` would
    # throw here: HCL evaluates both sides of `||` even when the left one is already true.
    condition     = var.max_allocated_storage == null ? true : var.max_allocated_storage > var.allocated_storage
    error_message = "max_allocated_storage must be strictly greater than allocated_storage, or null to disable autoscaling."
  }
}

variable "storage_type" {
  description = "EBS volume type backing the instance: gp3 for almost everything, io2 when a specific IOPS number is contractual."
  type        = string
  default     = "gp3"

  validation {
    condition     = contains(["gp2", "gp3", "io1", "io2"], var.storage_type)
    error_message = "storage_type must be gp2, gp3, io1 or io2."
  }
}

variable "multi_az" {
  description = "Run a synchronous standby in a second availability zone. Roughly doubles the instance cost and turns a zone failure into a ~60 second failover."
  type        = bool
  default     = false
}

variable "database_name" {
  description = "Name of the database created on first boot."
  type        = string
  default     = "app"

  validation {
    condition     = can(regex("^[a-zA-Z][a-zA-Z0-9_]{0,62}$", var.database_name))
    error_message = "database_name must start with a letter and contain only letters, digits and underscores."
  }
}

variable "master_username" {
  description = "Master user name. The password is generated by RDS and stored in Secrets Manager; it is never an input to this module."
  type        = string
  default     = "postgres"

  validation {
    condition     = can(regex("^[a-zA-Z][a-zA-Z0-9_]{0,62}$", var.master_username))
    error_message = "master_username must start with a letter and contain only letters, digits and underscores."
  }

  validation {
    condition     = !contains(["admin", "rdsadmin", "postgres_superuser"], lower(var.master_username))
    error_message = "admin and rdsadmin are reserved by RDS and the create call fails on them."
  }
}

variable "master_user_secret_kms_key_id" {
  description = "Customer-managed KMS key encrypting the master password secret. Null uses the aws/secretsmanager AWS-managed key."
  type        = string
  default     = null
}

variable "storage_kms_key_id" {
  description = "KMS key encrypting the storage volume, snapshots and Performance Insights data. Null uses the aws/rds AWS-managed key."
  type        = string
  default     = null
}

variable "port" {
  description = "TCP port the instance listens on."
  type        = number
  default     = 5432

  validation {
    condition     = var.port >= 1024 && var.port <= 65535
    error_message = "port must be between 1024 and 65535."
  }
}

variable "allowed_security_group_ids" {
  description = "Security groups allowed to connect to the database port. This is the intended way in: application security group in, everything else out."
  type        = list(string)
  default     = []
}

variable "allowed_cidr_blocks" {
  description = "CIDR blocks allowed to connect to the database port. Use sparingly; a security group reference survives a re-addressing of the network, a CIDR does not."
  type        = list(string)
  default     = []

  validation {
    condition     = alltrue([for c in var.allowed_cidr_blocks : can(cidrhost(c, 0))])
    error_message = "Every entry of allowed_cidr_blocks must be a valid IPv4 CIDR block."
  }

  validation {
    condition     = !contains(var.allowed_cidr_blocks, "0.0.0.0/0")
    error_message = "0.0.0.0/0 on a database port is never the intent. Name the application subnets or pass a security group."
  }
}

variable "backup_retention_period" {
  description = "Days of automated backups. Zero disables them, and with them point-in-time recovery."
  type        = number
  default     = 14

  validation {
    condition     = var.backup_retention_period >= 0 && var.backup_retention_period <= 35
    error_message = "backup_retention_period must be between 0 and 35 days."
  }
}

variable "backup_window" {
  description = "Daily window for the backup snapshot, UTC, as hh:mm-hh:mm."
  type        = string
  default     = "01:00-02:00"

  validation {
    condition     = can(regex("^([01][0-9]|2[0-3]):[0-5][0-9]-([01][0-9]|2[0-3]):[0-5][0-9]$", var.backup_window))
    error_message = "backup_window must look like 01:00-02:00 in UTC."
  }
}

variable "maintenance_window" {
  description = "Weekly window for minor version upgrades and OS patching, UTC, as ddd:hh:mm-ddd:hh:mm."
  type        = string
  default     = "sun:03:00-sun:05:00"

  validation {
    condition     = can(regex("^(mon|tue|wed|thu|fri|sat|sun):([01][0-9]|2[0-3]):[0-5][0-9]-(mon|tue|wed|thu|fri|sat|sun):([01][0-9]|2[0-3]):[0-5][0-9]$", var.maintenance_window))
    error_message = "maintenance_window must look like sun:03:00-sun:05:00, lowercase day names, in UTC."
  }

  validation {
    # RDS refuses a backup window that overlaps the maintenance window, but only several
    # minutes into the create call. Both are converted to minutes since midnight UTC and
    # compared as intervals. The guard matters: the ternary is what keeps substr from
    # running against a malformed string, since `||` would evaluate both sides regardless.
    condition = (
      can(regex("^([01][0-9]|2[0-3]):[0-5][0-9]-([01][0-9]|2[0-3]):[0-5][0-9]$", var.backup_window))
      && can(regex("^[a-z]{3}:([01][0-9]|2[0-3]):[0-5][0-9]-[a-z]{3}:([01][0-9]|2[0-3]):[0-5][0-9]$", var.maintenance_window))
      ? (
        tonumber(substr(var.backup_window, 6, 2)) * 60 + tonumber(substr(var.backup_window, 9, 2))
        <= tonumber(substr(var.maintenance_window, 4, 2)) * 60 + tonumber(substr(var.maintenance_window, 7, 2))
        ||
        tonumber(substr(var.maintenance_window, 14, 2)) * 60 + tonumber(substr(var.maintenance_window, 17, 2))
        <= tonumber(substr(var.backup_window, 0, 2)) * 60 + tonumber(substr(var.backup_window, 3, 2))
      )
      : true
    )
    error_message = "backup_window and maintenance_window overlap in time of day. RDS rejects that, but only minutes into the create call."
  }
}

variable "deletion_protection" {
  description = <<-EOT
    Refuse to delete the instance until this is turned off. Defaults to true: an accidental
    `terraform destroy` against the wrong workspace is the failure this exists for.
    Ephemeral environments should pass false explicitly, so the choice is visible in the diff.
  EOT
  type        = bool
  default     = true
}

variable "skip_final_snapshot" {
  description = "Delete the instance without taking a final snapshot. Only reasonable when the data is reproducible."
  type        = bool
  default     = false
}

variable "performance_insights_enabled" {
  description = "Collect Performance Insights. The 7-day tier is free and is the difference between diagnosing a slow query and guessing at one."
  type        = bool
  default     = true
}

variable "performance_insights_retention_period" {
  description = "Days of Performance Insights history: 7 (free), 731, or a multiple of 31 up to 731."
  type        = number
  default     = 7

  validation {
    condition     = var.performance_insights_retention_period == 7 || var.performance_insights_retention_period == 731 || var.performance_insights_retention_period % 31 == 0
    error_message = "performance_insights_retention_period must be 7, 731, or a multiple of 31."
  }

  validation {
    condition     = var.performance_insights_enabled || var.performance_insights_retention_period == 7
    error_message = "performance_insights_retention_period only has an effect while performance_insights_enabled is true; leave it at 7."
  }
}

variable "monitoring_interval" {
  description = "Enhanced monitoring granularity in seconds: 0 (off), 1, 5, 10, 15, 30 or 60. The module creates the monitoring role when this is not zero."
  type        = number
  default     = 60

  validation {
    condition     = contains([0, 1, 5, 10, 15, 30, 60], var.monitoring_interval)
    error_message = "monitoring_interval must be 0, 1, 5, 10, 15, 30 or 60."
  }
}

variable "enabled_cloudwatch_logs_exports" {
  description = "PostgreSQL log types shipped to CloudWatch: postgresql (the server log) and upgrade."
  type        = list(string)
  default     = ["postgresql", "upgrade"]

  validation {
    condition     = alltrue([for l in var.enabled_cloudwatch_logs_exports : contains(["postgresql", "upgrade"], l)])
    error_message = "PostgreSQL on RDS only exports postgresql and upgrade."
  }
}

variable "auto_minor_version_upgrade" {
  description = "Let RDS apply minor version upgrades inside the maintenance window."
  type        = bool
  default     = true
}

variable "apply_immediately" {
  description = "Apply changes now instead of waiting for the maintenance window. Some of them restart the instance."
  type        = bool
  default     = false
}

variable "parameters" {
  description = <<-EOT
    Database parameters, keyed by parameter name. `apply_method` is `immediate` for dynamic
    parameters and `pending-reboot` for static ones; getting it wrong makes the parameter
    look applied while the server is still running the old value.
  EOT

  type = map(object({
    value        = string
    apply_method = optional(string, "immediate")
  }))
  default = {}

  validation {
    condition     = alltrue([for p in var.parameters : contains(["immediate", "pending-reboot"], p.apply_method)])
    error_message = "apply_method must be immediate or pending-reboot."
  }
}

variable "tags" {
  description = "Tags applied to every resource the module creates."
  type        = map(string)
  default     = {}
}

variable "final_snapshot_identifier" {
  description = <<-EOT
    Name of the snapshot taken on destroy. Null derives `<identifier>-final`.

    Worth setting explicitly on an environment that is created and destroyed repeatedly:
    RDS refuses to create a snapshot whose name already exists, so the second destroy of
    the same identifier fails at the very end of the operation, with everything else
    already gone.
  EOT
  type        = string
  default     = null

  validation {
    condition     = var.final_snapshot_identifier == null ? true : can(regex("^[a-z][a-z0-9-]{0,254}[a-z0-9]$", var.final_snapshot_identifier))
    error_message = "final_snapshot_identifier must be lowercase letters, digits and hyphens, starting with a letter and not ending in a hyphen."
  }
}
